# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import domain_lookup_pb2 as domain__lookup__pb2


class DomainLookupServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDomain = channel.unary_unary(
                '/edu.cs244b.common.DomainLookupService/GetDomain',
                request_serializer=domain__lookup__pb2.HostName.SerializeToString,
                response_deserializer=domain__lookup__pb2.DNSRecord.FromString,
                )


class DomainLookupServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetDomain(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainLookupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomain,
                    request_deserializer=domain__lookup__pb2.HostName.FromString,
                    response_serializer=domain__lookup__pb2.DNSRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edu.cs244b.common.DomainLookupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DomainLookupService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu.cs244b.common.DomainLookupService/GetDomain',
            domain__lookup__pb2.HostName.SerializeToString,
            domain__lookup__pb2.DNSRecord.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
