# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain_lookup.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='domain_lookup.proto',
  package='edu.cs244b.common',
  syntax='proto3',
  serialized_options=b'\n\021edu.cs244b.commonB\022DomainLookupProtosP\001',
  serialized_pb=b'\n\x13\x64omain_lookup.proto\x12\x11\x65\x64u.cs244b.common\"\x18\n\x08HostName\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\tDNSRecord\x12\x10\n\x08hostName\x18\x01 \x01(\t\x12\x13\n\x0bipAddresses\x18\x02 \x03(\t2]\n\x13\x44omainLookupService\x12\x46\n\tGetDomain\x12\x1b.edu.cs244b.common.HostName\x1a\x1c.edu.cs244b.common.DNSRecordB)\n\x11\x65\x64u.cs244b.commonB\x12\x44omainLookupProtosP\x01\x62\x06proto3'
)




_HOSTNAME = _descriptor.Descriptor(
  name='HostName',
  full_name='edu.cs244b.common.HostName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='edu.cs244b.common.HostName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=66,
)


_DNSRECORD = _descriptor.Descriptor(
  name='DNSRecord',
  full_name='edu.cs244b.common.DNSRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostName', full_name='edu.cs244b.common.DNSRecord.hostName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipAddresses', full_name='edu.cs244b.common.DNSRecord.ipAddresses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['HostName'] = _HOSTNAME
DESCRIPTOR.message_types_by_name['DNSRecord'] = _DNSRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HostName = _reflection.GeneratedProtocolMessageType('HostName', (_message.Message,), {
  'DESCRIPTOR' : _HOSTNAME,
  '__module__' : 'domain_lookup_pb2'
  # @@protoc_insertion_point(class_scope:edu.cs244b.common.HostName)
  })
_sym_db.RegisterMessage(HostName)

DNSRecord = _reflection.GeneratedProtocolMessageType('DNSRecord', (_message.Message,), {
  'DESCRIPTOR' : _DNSRECORD,
  '__module__' : 'domain_lookup_pb2'
  # @@protoc_insertion_point(class_scope:edu.cs244b.common.DNSRecord)
  })
_sym_db.RegisterMessage(DNSRecord)


DESCRIPTOR._options = None

_DOMAINLOOKUPSERVICE = _descriptor.ServiceDescriptor(
  name='DomainLookupService',
  full_name='edu.cs244b.common.DomainLookupService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=120,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDomain',
    full_name='edu.cs244b.common.DomainLookupService.GetDomain',
    index=0,
    containing_service=None,
    input_type=_HOSTNAME,
    output_type=_DNSRECORD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOMAINLOOKUPSERVICE)

DESCRIPTOR.services_by_name['DomainLookupService'] = _DOMAINLOOKUPSERVICE

# @@protoc_insertion_point(module_scope)
